trigger:
- main
variables:
    env: dev
pool: 
  vmImage: ubuntu-latest
stages:
- stage: build
  jobs:
  - job: job1
    steps:
     - script: pwd
       displayName: "This is my first stage task"
     - script: echo $(foo)
       displayName:  Test Variable
- stage: Test
  dependsOn: build
  jobs: 
  - job: job2
    steps:
    - script: echo "This is another job"
      displayName: Another job  
    - script: echo $(Agent.WorkFolder)
      displayName: test predefined variables

