trigger:
- main
variables:
    env: dev
pool: 
  vmImage: ubuntu-latest
stages:
- stage: build
  jobs:
  - job: job1
    steps:
     - script: pwd
       displayName: "This is my first stage task"
     - script: echo $(foo)
       displayName:  Test Variable
- stage: Test
  jobs: 
  - job: job2
    steps:
    - script: echo "This is another job"
      displayName: Another job  


